export enum VideoStates {
  PLAY_VIDEO = 'PLAY_VIDEO',
  PAUSE_VIDEO = 'PAUSE_VIDEO',
  CHANGE_VIDEO = 'CHANGE_VIDEO',
  RESET_PAUSE_PLAY = 'RESET_PAUSE_PLAY',
  SET_TRANSITION = 'SET_TRANSITION'
}

export enum ClientStates {
  UPDATE_CLIENT_NAME,
  UPDATE_YOUTUBE_ID,
  UPDATE_CLIENT_LIST,
  UPDATE_CHAT_MESSAGES
}