export enum VideoStates {
  PLAY_VIDEO = 'PLAY_VIDEO',
  PAUSE_VIDEO = 'PAUSE_VIDEO',
  CHANGE_VIDEO = 'CHANGE_VIDEO',
  RESET_PAUSE_PLAY = 'RESET_PAUSE_PLAY',
  SEEK_VIDEO = 'SEEK_VIDEO',
}

export enum ClientStates {
  UPDATE_CLIENT_NAME,
  UPDATE_YOUTUBE_ID,
  UPDATE_CLIENT_LIST,
  UPDATE_CHAT_MESSAGES,
  UPDATE_PLAYLIST,
  DELETE_VIDEO,
  CHANGE_VIDEO,
}
